// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package systest contains autogenerated mocks.
package systest

import "github.com/stretchr/testify/mock"

import "syscall"

// Syscall is an autogenerated mock type for the Syscall type
type Syscall struct {
	mock.Mock
}

// Stat provides a mock function with given fields: mockeryArg0, mockeryArg1
func (mockerySelf *Syscall) Stat(mockeryArg0 string, mockeryArg1 *syscall.Stat_t) error {
	ret := mockerySelf.Called(mockeryArg0, mockeryArg1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *syscall.Stat_t) error); ok {
		r0 = rf(mockeryArg0, mockeryArg1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
